### ISSUE TITLE
Socket server keeps dying when kept idle for long

### ISSUE THREAD

**Issue by debarshri** [webbit/webbit#141]
I have been experiencing this recently.

Socket server keeps dying when kept idle for long. It is a normal behavior of a socket server?

**Comment by gabereiser** [comment]
can you elaborate?  A socket server is supposed to timeout any connections after a certain idle period.  How are you connecting to webbit and utilizing the connection?

**Comment by debarshri** [comment]
Well..it was application issue. Sorry for inconvience.
